wandb_version: 1

seed:
  desc: null
  value: 42
model:
  desc: null
  value:
    name: xgboost
    feature_dim: ???
    normalise_features: false
    eval: ???
    pcriterion: majority
    LOG_PATH: ../../ML4SpatialAnalysis/logs
    fnorm: minmax
    gcriterion: gcn
    gf_dim: 32
    logistic:
      penalty: null
      l1_ratio: 0.5
      solver: lbfgs
      max_iter: 1000
      tol: 1.0e-05
      random_state: ???
    gnn:
      gconv: gcn
      lr: 0.01
      nm_epochs: 20
      device: gpu
      logger: ???
      batch_size: 128
      fnorm: ???
      gcn:
        hidden_dim: ???
        input_dim: ???
        nm_class: 1
      ssgcn:
        hidden_dim: ???
        input_dim: ???
        nm_class: 1
    randomforest:
      n_estimators: 100
      criterion: gini
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1
      min_weight_fraction_leaf: 0
      max_features: sqrt
      max_leaf_nodes: null
      min_impurity_decrease: 0
      bootstrap: true
      oob_score: false
      n_jobs: 12
      warm_start: false
      class_weight: null
      ccp_alpha: 0.0
      random_state: ???
    xgboost:
      objective: binary:logistic
      max_depth: 3
      learning_rate: 0.1
      n_estimators: 100
attribution:
  desc: null
  value:
    top_k: 10
    filename: ???
    MODEL_PATH: /logmodels
dataset:
  desc: null
  value:
    DATA_PATH: ../../ML4SpatialAnalysis/data
    cell_filename: cell_table_size_normalized_cell_labels_corrected_labels
    response_filename: processed_response_enR
    gtype: cellcell
    k: 7
    gmethod: knn
    datasplit: split
    test_ratio: 0.3
    folds: 5
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711642049.97491
    t:
      1:
      - 1
      - 5
      - 6
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 6
      - 53
      - 54
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
